spring.application.name: cb-service

server:
  port : 8181

  spring.datasource:
    url: jdbc:postgresql://localhost:5432/cb-service
    username: postgres
    password: root

cbr:
  wsdl: https://cbr.ru/DailyInfoWebServ/DailyInfo.asmx?WSDL
  connection: 10000
  read: 10000


