
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ru.cbr.web;

import java.util.logging.Logger;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.4
 * Generated source version: 4.0.4
 *
 */

@jakarta.jws.WebService(
                      serviceName = "DailyInfo",
                      portName = "DailyInfoSoap12",
                      targetNamespace = "http://web.cbr.ru/",
                      wsdlLocation = "file:/C:/Users/Den/IdeaProjects/cb-service/src/main/resources/DailyInfoWebServ.wsdl",
                      endpointInterface = "ru.cbr.web.DailyInfoSoap")

public class DailyInfoSoap12Impl implements DailyInfoSoap {

    private static final Logger LOG = Logger.getLogger(DailyInfoSoap12Impl.class.getName());

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#repoDebtUSDXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.RepoDebtUSDXMLResponse.RepoDebtUSDXMLResult repoDebtUSDXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation repoDebtUSDXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.RepoDebtUSDXMLResponse.RepoDebtUSDXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#repoDebtXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.RepoDebtXMLResponse.RepoDebtXMLResult repoDebtXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation repoDebtXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.RepoDebtXMLResponse.RepoDebtXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#ostatDynamic(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.OstatDynamicResponse.OstatDynamicResult ostatDynamic(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation ostatDynamic");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.OstatDynamicResponse.OstatDynamicResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#roiSfix(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.ROISfixResponse.ROISfixResult roiSfix(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation roiSfix");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.ROISfixResponse.ROISfixResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#ruoniaSVXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.RuoniaSVXMLResponse.RuoniaSVXMLResult ruoniaSVXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation ruoniaSVXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.RuoniaSVXMLResponse.RuoniaSVXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#ostatDepoNew(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.OstatDepoNewResponse.OstatDepoNewResult ostatDepoNew(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation ostatDepoNew");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.OstatDepoNewResponse.OstatDepoNewResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#saldoXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.SaldoXMLResponse.SaldoXMLResult saldoXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation saldoXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.SaldoXMLResponse.SaldoXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#ostatDepoXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.OstatDepoXMLResponse.OstatDepoXMLResult ostatDepoXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation ostatDepoXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.OstatDepoXMLResponse.OstatDepoXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#newsInfo(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.NewsInfoResponse.NewsInfoResult newsInfo(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation newsInfo");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.NewsInfoResponse.NewsInfoResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#repoDebt2(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.RepoDebt2Response.RepoDebt2Result repoDebt2(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation repoDebt2");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.RepoDebt2Response.RepoDebt2Result _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#mrrfXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.MrrfXMLResponse.MrrfXMLResult mrrfXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation mrrfXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.MrrfXMLResponse.MrrfXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#getLatestReutersDateTime()*
     */
    public javax.xml.datatype.XMLGregorianCalendar getLatestReutersDateTime() {
        LOG.info("Executing operation getLatestReutersDateTime");
        try {
            javax.xml.datatype.XMLGregorianCalendar _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#mrrf7D(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.Mrrf7DResponse.Mrrf7DResult mrrf7D(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation mrrf7D");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.Mrrf7DResponse.Mrrf7DResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#roiSfixXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.ROISfixXMLResponse.ROISfixXMLResult roiSfixXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation roiSfixXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.ROISfixXMLResponse.ROISfixXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#dragMetDynamic(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.DragMetDynamicResponse.DragMetDynamicResult dragMetDynamic(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation dragMetDynamic");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.DragMetDynamicResponse.DragMetDynamicResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#enumValutesXML(boolean seld)*
     */
    public ru.cbr.web.EnumValutesXMLResponse.EnumValutesXMLResult enumValutesXML(boolean seld) {
        LOG.info("Executing operation enumValutesXML");
        System.out.println(seld);
        try {
            ru.cbr.web.EnumValutesXMLResponse.EnumValutesXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#getSeldCursOnDate(javax.xml.datatype.XMLGregorianCalendar onDate)*
     */
    public ru.cbr.web.GetSeldCursOnDateResponse.GetSeldCursOnDateResult getSeldCursOnDate(javax.xml.datatype.XMLGregorianCalendar onDate) {
        LOG.info("Executing operation getSeldCursOnDate");
        System.out.println(onDate);
        try {
            ru.cbr.web.GetSeldCursOnDateResponse.GetSeldCursOnDateResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#allDataInfoXML()*
     */
    public ru.cbr.web.AllDataInfoXMLResponse.AllDataInfoXMLResult allDataInfoXML() {
        LOG.info("Executing operation allDataInfoXML");
        try {
            ru.cbr.web.AllDataInfoXMLResponse.AllDataInfoXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#keyRate(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.KeyRateResponse.KeyRateResult keyRate(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation keyRate");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.KeyRateResponse.KeyRateResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#ostatDepo(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.OstatDepoResponse.OstatDepoResult ostatDepo(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation ostatDepo");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.OstatDepoResponse.OstatDepoResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#overnight(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.OvernightResponse.OvernightResult overnight(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation overnight");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.OvernightResponse.OvernightResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#enumValutes(boolean seld)*
     */
    public ru.cbr.web.EnumValutesResponse.EnumValutesResult enumValutes(boolean seld) {
        LOG.info("Executing operation enumValutes");
        System.out.println(seld);
        try {
            ru.cbr.web.EnumValutesResponse.EnumValutesResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#mkrxml(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.MKRXMLResponse.MKRXMLResult mkrxml(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation mkrxml");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.MKRXMLResponse.MKRXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#ostatDynamicXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.OstatDynamicXMLResponse.OstatDynamicXMLResult ostatDynamicXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation ostatDynamicXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.OstatDynamicXMLResponse.OstatDynamicXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#biCurBaseXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.BiCurBaseXMLResponse.BiCurBaseXMLResult biCurBaseXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation biCurBaseXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.BiCurBaseXMLResponse.BiCurBaseXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#valIntDayXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.ValIntDayXMLResponse.ValIntDayXMLResult valIntDayXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation valIntDayXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.ValIntDayXMLResponse.ValIntDayXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#getCursOnDate(javax.xml.datatype.XMLGregorianCalendar onDate)*
     */
    public ru.cbr.web.GetCursOnDateResponse.GetCursOnDateResult getCursOnDate(javax.xml.datatype.XMLGregorianCalendar onDate) {
        LOG.info("Executing operation getCursOnDate");
        System.out.println(onDate);
        try {
            ru.cbr.web.GetCursOnDateResponse.GetCursOnDateResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#swapInfoSellUSDXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.SwapInfoSellUSDXMLResponse.SwapInfoSellUSDXMLResult swapInfoSellUSDXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation swapInfoSellUSDXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.SwapInfoSellUSDXMLResponse.SwapInfoSellUSDXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#mrrf(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.MrrfResponse.MrrfResult mrrf(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation mrrf");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.MrrfResponse.MrrfResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#swapDynamic(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.SwapDynamicResponse.SwapDynamicResult swapDynamic(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation swapDynamic");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.SwapDynamicResponse.SwapDynamicResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#depoDynamic(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.DepoDynamicResponse.DepoDynamicResult depoDynamic(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation depoDynamic");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.DepoDynamicResponse.DepoDynamicResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#getLatestDateSeld()*
     */
    public java.lang.String getLatestDateSeld() {
        LOG.info("Executing operation getLatestDateSeld");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#swapDynamicXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.SwapDynamicXMLResponse.SwapDynamicXMLResult swapDynamicXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation swapDynamicXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.SwapDynamicXMLResponse.SwapDynamicXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#bliquidity(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.BliquidityResponse.BliquidityResult bliquidity(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation bliquidity");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.BliquidityResponse.BliquidityResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#swapInfoSellVolXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.SwapInfoSellVolXMLResponse.SwapInfoSellVolXMLResult swapInfoSellVolXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation swapInfoSellVolXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.SwapInfoSellVolXMLResponse.SwapInfoSellVolXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#omodInfoXML()*
     */
    public ru.cbr.web.OmodInfoXMLResponse.OmodInfoXMLResult omodInfoXML() {
        LOG.info("Executing operation omodInfoXML");
        try {
            ru.cbr.web.OmodInfoXMLResponse.OmodInfoXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#keyRateXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.KeyRateXMLResponse.KeyRateXMLResult keyRateXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation keyRateXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.KeyRateXMLResponse.KeyRateXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#fixingBaseXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.FixingBaseXMLResponse.FixingBaseXMLResult fixingBaseXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation fixingBaseXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.FixingBaseXMLResponse.FixingBaseXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#depoDynamicXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.DepoDynamicXMLResponse.DepoDynamicXMLResult depoDynamicXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation depoDynamicXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.DepoDynamicXMLResponse.DepoDynamicXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#enumReutersValutesXML()*
     */
    public ru.cbr.web.EnumReutersValutesXMLResponse.EnumReutersValutesXMLResult enumReutersValutesXML() {
        LOG.info("Executing operation enumReutersValutesXML");
        try {
            ru.cbr.web.EnumReutersValutesXMLResponse.EnumReutersValutesXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#dv(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.DVResponse.DVResult dv(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation dv");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.DVResponse.DVResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#biCurBacket()*
     */
    public ru.cbr.web.BiCurBacketResponse.BiCurBacketResult biCurBacket() {
        LOG.info("Executing operation biCurBacket");
        try {
            ru.cbr.web.BiCurBacketResponse.BiCurBacketResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#fixingBase(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.FixingBaseResponse.FixingBaseResult fixingBase(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation fixingBase");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.FixingBaseResponse.FixingBaseResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#getLatestDateTime()*
     */
    public javax.xml.datatype.XMLGregorianCalendar getLatestDateTime() {
        LOG.info("Executing operation getLatestDateTime");
        try {
            javax.xml.datatype.XMLGregorianCalendar _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#biCurBase(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.BiCurBaseResponse.BiCurBaseResult biCurBase(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation biCurBase");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.BiCurBaseResponse.BiCurBaseResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#getReutersCursDynamicXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate, int numCode)*
     */
    public ru.cbr.web.GetReutersCursDynamicXMLResponse.GetReutersCursDynamicXMLResult getReutersCursDynamicXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate, int numCode) {
        LOG.info("Executing operation getReutersCursDynamicXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        System.out.println(numCode);
        try {
            ru.cbr.web.GetReutersCursDynamicXMLResponse.GetReutersCursDynamicXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#dragMetDynamicXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.DragMetDynamicXMLResponse.DragMetDynamicXMLResult dragMetDynamicXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation dragMetDynamicXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.DragMetDynamicXMLResponse.DragMetDynamicXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#getReutersCursOnDateXML(javax.xml.datatype.XMLGregorianCalendar onDate)*
     */
    public ru.cbr.web.GetReutersCursOnDateXMLResponse.GetReutersCursOnDateXMLResult getReutersCursOnDateXML(javax.xml.datatype.XMLGregorianCalendar onDate) {
        LOG.info("Executing operation getReutersCursOnDateXML");
        System.out.println(onDate);
        try {
            ru.cbr.web.GetReutersCursOnDateXMLResponse.GetReutersCursOnDateXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#getSeldCursOnDateXML(javax.xml.datatype.XMLGregorianCalendar onDate)*
     */
    public ru.cbr.web.GetSeldCursOnDateXMLResponse.GetSeldCursOnDateXMLResult getSeldCursOnDateXML(javax.xml.datatype.XMLGregorianCalendar onDate) {
        LOG.info("Executing operation getSeldCursOnDateXML");
        System.out.println(onDate);
        try {
            ru.cbr.web.GetSeldCursOnDateXMLResponse.GetSeldCursOnDateXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#xVolXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.XVolXMLResponse.XVolXMLResult xVolXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation xVolXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.XVolXMLResponse.XVolXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#coinsBaseXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.CoinsBaseXMLResponse.CoinsBaseXMLResult coinsBaseXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation coinsBaseXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.CoinsBaseXMLResponse.CoinsBaseXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#swapInfoSellVol(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.SwapInfoSellVolResponse.SwapInfoSellVolResult swapInfoSellVol(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation swapInfoSellVol");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.SwapInfoSellVolResponse.SwapInfoSellVolResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#ruonia(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.RuoniaResponse.RuoniaResult ruonia(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation ruonia");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.RuoniaResponse.RuoniaResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#swapDayTotalXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.SwapDayTotalXMLResponse.SwapDayTotalXMLResult swapDayTotalXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation swapDayTotalXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.SwapDayTotalXMLResponse.SwapDayTotalXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#mkr(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.MKRResponse.MKRResult mkr(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation mkr");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.MKRResponse.MKRResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#getReutersCursOnDate(javax.xml.datatype.XMLGregorianCalendar onDate)*
     */
    public ru.cbr.web.GetReutersCursOnDateResponse.GetReutersCursOnDateResult getReutersCursOnDate(javax.xml.datatype.XMLGregorianCalendar onDate) {
        LOG.info("Executing operation getReutersCursOnDate");
        System.out.println(onDate);
        try {
            ru.cbr.web.GetReutersCursOnDateResponse.GetReutersCursOnDateResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#getLatestDateTimeSeld()*
     */
    public javax.xml.datatype.XMLGregorianCalendar getLatestDateTimeSeld() {
        LOG.info("Executing operation getLatestDateTimeSeld");
        try {
            javax.xml.datatype.XMLGregorianCalendar _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#biCurBacketXML()*
     */
    public ru.cbr.web.BiCurBacketXMLResponse.BiCurBacketXMLResult biCurBacketXML() {
        LOG.info("Executing operation biCurBacketXML");
        try {
            ru.cbr.web.BiCurBacketXMLResponse.BiCurBacketXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#saldo(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.SaldoResponse.SaldoResult saldo(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation saldo");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.SaldoResponse.SaldoResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#xVol(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.XVolResponse.XVolResult xVol(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation xVol");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.XVolResponse.XVolResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#ruoniaSV(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.RuoniaSVResponse.RuoniaSVResult ruoniaSV(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation ruoniaSV");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.RuoniaSVResponse.RuoniaSVResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#repoDebt2XML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.RepoDebt2XMLResponse.RepoDebt2XMLResult repoDebt2XML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation repoDebt2XML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.RepoDebt2XMLResponse.RepoDebt2XMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#swapInfoSellUSD(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.SwapInfoSellUSDResponse.SwapInfoSellUSDResult swapInfoSellUSD(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation swapInfoSellUSD");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.SwapInfoSellUSDResponse.SwapInfoSellUSDResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#swapMonthTotalXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.SwapMonthTotalXMLResponse.SwapMonthTotalXMLResult swapMonthTotalXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation swapMonthTotalXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.SwapMonthTotalXMLResponse.SwapMonthTotalXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#swapMonthTotal(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.SwapMonthTotalResponse.SwapMonthTotalResult swapMonthTotal(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation swapMonthTotal");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.SwapMonthTotalResponse.SwapMonthTotalResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#bauctionXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.BauctionXMLResponse.BauctionXMLResult bauctionXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation bauctionXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.BauctionXMLResponse.BauctionXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#mainInfoXML()*
     */
    public ru.cbr.web.MainInfoXMLResponse.MainInfoXMLResult mainInfoXML() {
        LOG.info("Executing operation mainInfoXML");
        try {
            ru.cbr.web.MainInfoXMLResponse.MainInfoXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#enumReutersValutes()*
     */
    public ru.cbr.web.EnumReutersValutesResponse.EnumReutersValutesResult enumReutersValutes() {
        LOG.info("Executing operation enumReutersValutes");
        try {
            ru.cbr.web.EnumReutersValutesResponse.EnumReutersValutesResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#swapInfoSellUSDVol(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.SwapInfoSellUSDVolResponse.SwapInfoSellUSDVolResult swapInfoSellUSDVol(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation swapInfoSellUSDVol");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.SwapInfoSellUSDVolResponse.SwapInfoSellUSDVolResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#repoDebt(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.RepoDebtResponse.RepoDebtResult repoDebt(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation repoDebt");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.RepoDebtResponse.RepoDebtResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#getCursDynamicXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate, java.lang.String valutaCode)*
     */
    public ru.cbr.web.GetCursDynamicXMLResponse.GetCursDynamicXMLResult getCursDynamicXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate, java.lang.String valutaCode) {
        LOG.info("Executing operation getCursDynamicXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        System.out.println(valutaCode);
        try {
            ru.cbr.web.GetCursDynamicXMLResponse.GetCursDynamicXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#repoDebtUSD(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.RepoDebtUSDResponse.RepoDebtUSDResult repoDebtUSD(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation repoDebtUSD");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.RepoDebtUSDResponse.RepoDebtUSDResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#getCursDynamic(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate, java.lang.String valutaCode)*
     */
    public ru.cbr.web.GetCursDynamicResponse.GetCursDynamicResult getCursDynamic(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate, java.lang.String valutaCode) {
        LOG.info("Executing operation getCursDynamic");
        System.out.println(fromDate);
        System.out.println(toDate);
        System.out.println(valutaCode);
        try {
            ru.cbr.web.GetCursDynamicResponse.GetCursDynamicResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#getCursOnDateXML(javax.xml.datatype.XMLGregorianCalendar onDate)*
     */
    public ru.cbr.web.GetCursOnDateXMLResponse.GetCursOnDateXMLResult getCursOnDateXML(javax.xml.datatype.XMLGregorianCalendar onDate) {
        LOG.info("Executing operation getCursOnDateXML");
        System.out.println(onDate);
        try {
            ru.cbr.web.GetCursOnDateXMLResponse.GetCursOnDateXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#swapInfoSellUSDVolXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.SwapInfoSellUSDVolXMLResponse.SwapInfoSellUSDVolXMLResult swapInfoSellUSDVolXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation swapInfoSellUSDVolXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.SwapInfoSellUSDVolXMLResponse.SwapInfoSellUSDVolXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#mrrf7DXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.Mrrf7DXMLResponse.Mrrf7DXMLResult mrrf7DXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation mrrf7DXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.Mrrf7DXMLResponse.Mrrf7DXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#swapInfoSell(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.SwapInfoSellResponse.SwapInfoSellResult swapInfoSell(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation swapInfoSell");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.SwapInfoSellResponse.SwapInfoSellResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#newsInfoXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.NewsInfoXMLResponse.NewsInfoXMLResult newsInfoXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation newsInfoXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.NewsInfoXMLResponse.NewsInfoXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#swapDayTotal(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.SwapDayTotalResponse.SwapDayTotalResult swapDayTotal(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation swapDayTotal");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.SwapDayTotalResponse.SwapDayTotalResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#coinsBase(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.CoinsBaseResponse.CoinsBaseResult coinsBase(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation coinsBase");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.CoinsBaseResponse.CoinsBaseResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#bauction(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.BauctionResponse.BauctionResult bauction(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation bauction");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.BauctionResponse.BauctionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#ostatDepoNewXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.OstatDepoNewXMLResponse.OstatDepoNewXMLResult ostatDepoNewXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation ostatDepoNewXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.OstatDepoNewXMLResponse.OstatDepoNewXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#dvxml(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.DVXMLResponse.DVXMLResult dvxml(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation dvxml");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.DVXMLResponse.DVXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#overnightXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.OvernightXMLResponse.OvernightXMLResult overnightXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation overnightXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.OvernightXMLResponse.OvernightXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#swapInfoSellXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.SwapInfoSellXMLResponse.SwapInfoSellXMLResult swapInfoSellXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation swapInfoSellXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.SwapInfoSellXMLResponse.SwapInfoSellXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#bliquidityXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.BliquidityXMLResponse.BliquidityXMLResult bliquidityXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation bliquidityXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.BliquidityXMLResponse.BliquidityXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#getLatestDate()*
     */
    public java.lang.String getLatestDate() {
        LOG.info("Executing operation getLatestDate");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#ruoniaXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.RuoniaXMLResponse.RuoniaXMLResult ruoniaXML(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation ruoniaXML");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.RuoniaXMLResponse.RuoniaXMLResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#getReutersCursDynamic(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate, int numCode)*
     */
    public ru.cbr.web.GetReutersCursDynamicResponse.GetReutersCursDynamicResult getReutersCursDynamic(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate, int numCode) {
        LOG.info("Executing operation getReutersCursDynamic");
        System.out.println(fromDate);
        System.out.println(toDate);
        System.out.println(numCode);
        try {
            ru.cbr.web.GetReutersCursDynamicResponse.GetReutersCursDynamicResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ru.cbr.web.DailyInfoSoap#valIntDay(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ru.cbr.web.ValIntDayResponse.ValIntDayResult valIntDay(javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation valIntDay");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ru.cbr.web.ValIntDayResponse.ValIntDayResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
